"""Unified error codes for the KB Platform."""

from enum import StrEnum


class ErrorCode(StrEnum):
    # Auth
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_INSUFFICIENT_ROLE = "AUTH_INSUFFICIENT_ROLE"
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID"

    # Project
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_NAME_DUPLICATE = "PROJECT_NAME_DUPLICATE"

    # Asset
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_DUPLICATE_HASH = "ASSET_DUPLICATE_HASH"
    ASSET_TYPE_NOT_ALLOWED = "ASSET_TYPE_NOT_ALLOWED"
    ASSET_TOO_LARGE = "ASSET_TOO_LARGE"

    # Architecture
    ARCH_NOT_FOUND = "ARCH_NOT_FOUND"
    ARCH_NODE_NOT_FOUND = "ARCH_NODE_NOT_FOUND"
    ARCH_ALREADY_PUBLISHED = "ARCH_ALREADY_PUBLISHED"

    # Knowledge Doc
    DOC_NOT_FOUND = "DOC_NOT_FOUND"
    DOC_ALREADY_PUBLISHED = "DOC_ALREADY_PUBLISHED"

    # Job
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_ALREADY_RUNNING = "JOB_ALREADY_RUNNING"

    # Conflict
    CONFLICT_NOT_FOUND = "CONFLICT_NOT_FOUND"
    CONFLICT_ALREADY_RESOLVED = "CONFLICT_ALREADY_RESOLVED"

    # Model Config
    MODEL_PROVIDER_NOT_FOUND = "MODEL_PROVIDER_NOT_FOUND"
    MODEL_ROUTE_NOT_FOUND = "MODEL_ROUTE_NOT_FOUND"
    MODEL_PROVIDER_UNREACHABLE = "MODEL_PROVIDER_UNREACHABLE"

    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"

    # System
    SYSTEM_INTERNAL_ERROR = "SYSTEM_INTERNAL_ERROR"
    SYSTEM_RATE_LIMITED = "SYSTEM_RATE_LIMITED"
    SYSTEM_SSRF_BLOCKED = "SYSTEM_SSRF_BLOCKED"
