"""Write derived KBSQL outputs back into Hogwarts-KB markdown files.

Safety contract (enforced by every public function):

1. Only writes inside `settings.writer_allowed_paths` (default:
   wiki/summaries/, wiki/analyses/). NEVER raw-sources/ or lessons/.
2. Always wraps content with valid frontmatter (title, type, created,
   updated, updated_by=kbsql-bridge[bot], sources, related, tags).
3. Acquires a 30s timeout lock on .git/index.lock before writing — if
   obsidian-git is mid-commit, we wait or bail (never overlap).
4. After writing, commits with `bridge:` prefix and pushes if
   HOGWARTS_KB_AUTO_PUSH=true.

The write API is sync (not async) because GitPython is sync and the
volume is low (one write per ingest, not per request).
"""

from __future__ import annotations

import logging
import time
from datetime import date, datetime
from pathlib import Path
from typing import Any

import frontmatter
from git import Actor, Repo
from git.exc import GitCommandError

from ..config import get_settings

# Bot identity used for all bridge-authored commits.
# Matches Hogwarts-KB's `.bridge-config.yml > git.bot_author_*` fields.
BRIDGE_BOT_NAME = "kbsql-bridge[bot]"
BRIDGE_BOT_EMAIL = "bridge@kb-platform.local"

logger = logging.getLogger(__name__)


class KBWriteError(RuntimeError):
    """Raised when bridge cannot safely write to KB."""


class GitLockTimeout(KBWriteError):
    """Raised when .git/index.lock did not clear within timeout."""


def _wait_for_git_lock(repo_path: Path, timeout_s: int) -> None:
    """Block until .git/index.lock clears. Raise GitLockTimeout if not."""
    lock = repo_path / ".git" / "index.lock"
    deadline = time.monotonic() + timeout_s
    while lock.exists():
        if time.monotonic() > deadline:
            raise GitLockTimeout(
                f"git lock {lock} still present after {timeout_s}s — "
                "obsidian-git may be stuck. Resolve manually."
            )
        time.sleep(0.5)


def _check_path_allowed(target: Path, kb_root: Path, allowed_subdirs: list[str]) -> None:
    """Reject any write outside allowed sub-folders. Raises KBWriteError."""
    target_abs = target.resolve()
    rel = str(target_abs.relative_to(kb_root.resolve()))
    if not any(rel.startswith(sub.rstrip("/") + "/") for sub in allowed_subdirs):
        raise KBWriteError(
            f"Refusing to write outside allowed paths. "
            f"Target {rel!r} not in {allowed_subdirs}"
        )


def _build_frontmatter(
    *,
    title: str,
    page_type: str,
    slug: str,
    sources: list[str] | None = None,
    related: list[str] | None = None,
    tags: list[str] | None = None,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Construct frontmatter dict per Hogwarts-KB SCHEMA.md.

    Includes `session_id` per global CLAUDE.md "知识库写入铁律" — without
    this, kb-index.py cannot index bridge-written files and the p-chain
    lineage breaks. Channel prefix is `cc:` (Claude Code) since the bridge
    is invoked by Claude-family agents.
    """
    today_iso = date.today().isoformat()
    fm: dict[str, Any] = {
        "title": title,
        "type": page_type,
        "created": today_iso,
        "updated": today_iso,
        "updated_by": BRIDGE_BOT_NAME,
        "sources": sources or [],
        "related": related or [],
        "tags": tags or [],
        # P-chain lineage fields (CLAUDE.md mandate)
        "session_id": f"cc:{today_iso}-kbsql-bridge-{slug}",
        "parent_session_id": None,
        "source": "claude-code-bridge",
    }
    if extra:
        fm.update(extra)
    return fm


def _write_file_with_frontmatter(
    target: Path, body: str, fm: dict[str, Any]
) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    post = frontmatter.Post(body, **fm)
    target.write_text(frontmatter.dumps(post) + "\n", encoding="utf-8")


def _commit_and_push(
    repo_path: Path,
    target: Path,
    commit_message: str,
    *,
    auto_push: bool,
    branch: str,
) -> str:
    """Stage, commit, optionally push. Returns the commit SHA."""
    repo = Repo(repo_path)
    rel = str(target.relative_to(repo_path))
    repo.git.add(rel)

    # Check if there's actually something to commit (idempotent writes)
    if not repo.is_dirty(index=True, working_tree=False, untracked_files=True):
        logger.info("No changes to commit for %s", rel)
        return repo.head.commit.hexsha

    full_msg = (
        f"{commit_message}\n\n"
        f"Auto-generated by KBSQL bridge service.\n"
        f"Co-Authored-By: {BRIDGE_BOT_NAME} <{BRIDGE_BOT_EMAIL}>\n"
    )
    # Explicit bot author/committer so commits are attributable to the bridge
    # (per dev-plan-v0.53 §v0.53.6: author = kbsql-bridge[bot]).
    bot_actor = Actor(BRIDGE_BOT_NAME, BRIDGE_BOT_EMAIL)
    logger.info("Committing %s as %s <%s>", rel, BRIDGE_BOT_NAME, BRIDGE_BOT_EMAIL)
    commit = repo.index.commit(full_msg, author=bot_actor, committer=bot_actor)

    if auto_push:
        try:
            origin = repo.remote(name="origin")
            origin.push(refspec=f"{branch}:{branch}")
            logger.info("Pushed %s to origin/%s", commit.hexsha[:8], branch)
        except GitCommandError as e:
            logger.error("git push failed: %s", e)
            raise KBWriteError(f"git push failed: {e}") from e
    return commit.hexsha


# ----- public write APIs ------------------------------------------------------

def write_summary_to_kb(
    *,
    title: str,
    body: str,
    sources: list[str] | None = None,
    related: list[str] | None = None,
    tags: list[str] | None = None,
    slug: str | None = None,
    extra_frontmatter: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Write a summary into wiki/summaries/{slug}.md.

    Args:
        title: human-readable title (also used to derive slug if not given)
        body: the markdown body (no frontmatter — we add it)
        sources: list of source paths (e.g. ["raw-sources/x.md"])
        related: list of related wiki pages (e.g. ["wiki/concepts/y"])
        tags: list of tags
        slug: filename slug; if None, derived from title
        extra_frontmatter: additional frontmatter fields

    Returns:
        {"path": str, "commit_sha": str, "wrote_bytes": int}
    """
    return _write_internal(
        page_type="summary",
        subdir="wiki/summaries",
        title=title,
        body=body,
        sources=sources,
        related=related,
        tags=tags,
        slug=slug,
        extra_frontmatter=extra_frontmatter,
        commit_message=f"bridge: add/update summary — {title}",
    )


def write_analysis_to_kb(
    *,
    title: str,
    body: str,
    sources: list[str] | None = None,
    related: list[str] | None = None,
    tags: list[str] | None = None,
    slug: str | None = None,
    extra_frontmatter: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Write an analysis into wiki/analyses/{slug}.md."""
    return _write_internal(
        page_type="analysis",
        subdir="wiki/analyses",
        title=title,
        body=body,
        sources=sources,
        related=related,
        tags=tags,
        slug=slug,
        extra_frontmatter=extra_frontmatter,
        commit_message=f"bridge: add/update analysis — {title}",
    )


def augment_existing_in_place(
    *,
    relative_path: str,
    augmented_full_text: str,
    expected_marker_start: str = "<!-- bridge-visual:start",
    expected_marker_end: str = "<!-- bridge-visual:end -->",
) -> dict[str, Any]:
    """Overwrite an existing markdown file with a bridge-visual-augmented version.

    SAFETY CONTRACT (v0.54+):
    1. Target MUST already exist (we don't create new files via this path)
    2. Target MUST be a .md file
    3. Target MUST live anywhere INSIDE kb_root (any layer — concept/howto/etc.)
       BUT the augmented_full_text MUST contain bridge-visual markers
       (proves it actually came from the augmenter and not arbitrary input)
    4. Bytes diff outside the markers should be zero (we DON'T enforce this
       at runtime — augmenter guarantees it; if a buggy augmenter modifies
       non-marker content, the user's git diff will catch it)
    5. Auto-commit + optional push (same git lock contract as other writers)

    This is the ONLY public API that can modify wiki/concepts/, wiki/howtos/,
    wiki/entities/, lessons/, memory/, raw-sources/. ALL other writes still go
    through write_summary_to_kb / write_analysis_to_kb (restricted folders).

    Args:
        relative_path: KB-relative path (e.g. "wiki/howtos/foo.md")
        augmented_full_text: full file content with frontmatter + body
        expected_marker_start / _end: safety check — must appear in text

    Returns:
        {"path", "commit_sha", "wrote_bytes", "auto_pushed", "skipped"}
        where skipped=True means content was identical (no commit).
    """
    settings = get_settings()
    kb_root = settings.hogwarts_kb_path
    if not kb_root.exists():
        raise KBWriteError(f"KB path does not exist: {kb_root}")
    if not (kb_root / ".git").exists():
        raise KBWriteError(f"KB path is not a git repo: {kb_root}")

    # 1. file extension guard
    if not relative_path.endswith(".md"):
        raise KBWriteError(
            f"augment_existing_in_place: only .md files allowed, got {relative_path}"
        )

    # 2. marker guard (proves this came from bridge-visual, not arbitrary text)
    if expected_marker_start not in augmented_full_text:
        raise KBWriteError(
            "augment_existing_in_place: text missing bridge-visual marker; "
            "refusing to write (safety check)."
        )
    if expected_marker_end not in augmented_full_text:
        raise KBWriteError(
            "augment_existing_in_place: text missing bridge-visual end marker; "
            "refusing to write."
        )

    target = (kb_root / relative_path).resolve()
    # 3. path traversal guard
    try:
        target.relative_to(kb_root.resolve())
    except ValueError as e:
        raise KBWriteError(
            f"Path escapes KB root: {relative_path}"
        ) from e
    # 4. existence guard
    if not target.is_file():
        raise KBWriteError(
            f"Target file does not exist (use write_summary_to_kb / write_analysis_to_kb "
            f"to create new files): {relative_path}"
        )

    _wait_for_git_lock(kb_root, settings.writer_git_lock_timeout_s)

    # Idempotent skip if content already identical
    current = target.read_text(encoding="utf-8")
    if current == augmented_full_text:
        return {
            "path": relative_path,
            "commit_sha": "(unchanged)",
            "wrote_bytes": 0,
            "auto_pushed": False,
            "skipped": True,
        }

    target.write_text(augmented_full_text, encoding="utf-8")
    wrote = target.stat().st_size

    commit_sha = _commit_and_push(
        kb_root,
        target,
        f"bridge-visual: augment {relative_path}",
        auto_push=settings.hogwarts_kb_auto_push,
        branch=settings.hogwarts_kb_branch,
    )

    return {
        "path": relative_path,
        "commit_sha": commit_sha,
        "wrote_bytes": wrote,
        "auto_pushed": settings.hogwarts_kb_auto_push,
        "skipped": False,
    }


def _slugify(s: str) -> str:
    import re
    s = s.strip().lower()
    s = re.sub(r"[^\w\u4e00-\u9fff\s-]", "", s)
    s = re.sub(r"\s+", "-", s)
    return s.strip("-") or "untitled"


def _write_internal(
    *,
    page_type: str,
    subdir: str,
    title: str,
    body: str,
    sources: list[str] | None,
    related: list[str] | None,
    tags: list[str] | None,
    slug: str | None,
    extra_frontmatter: dict[str, Any] | None,
    commit_message: str,
) -> dict[str, Any]:
    settings = get_settings()
    kb_root = settings.hogwarts_kb_path
    if not kb_root.exists():
        raise KBWriteError(f"KB path does not exist: {kb_root}")
    if not (kb_root / ".git").exists():
        raise KBWriteError(f"KB path is not a git repo: {kb_root}")

    actual_slug = slug or _slugify(title)
    target = kb_root / subdir / f"{actual_slug}.md"

    _check_path_allowed(target, kb_root, settings.writer_allowed_paths)
    _wait_for_git_lock(kb_root, settings.writer_git_lock_timeout_s)

    fm = _build_frontmatter(
        title=title,
        page_type=page_type,
        slug=actual_slug,
        sources=sources,
        related=related,
        tags=tags,
        extra=extra_frontmatter,
    )
    _write_file_with_frontmatter(target, body, fm)
    wrote = target.stat().st_size

    commit_sha = _commit_and_push(
        kb_root,
        target,
        commit_message,
        auto_push=settings.hogwarts_kb_auto_push,
        branch=settings.hogwarts_kb_branch,
    )

    return {
        "path": str(target.relative_to(kb_root)),
        "commit_sha": commit_sha,
        "wrote_bytes": wrote,
        "auto_pushed": settings.hogwarts_kb_auto_push,
    }
